# Render Blueprint Configuration
# One-click deploy for Bylaws Amendment Tracker
# Documentation: /docs/RENDER_DEPLOYMENT.md

services:
  - type: web
    name: bylaws-amendment-tracker
    env: node
    region: oregon  # Free tier available in Oregon
    plan: free      # Options: free, starter ($7/mo), standard ($25/mo)

    # Build & Start
    buildCommand: npm install
    startCommand: npm start

    # Health Check
    healthCheckPath: /api/health

    # Auto-deploy on git push to main branch
    autoDeploy: true

    # Environment Variables
    envVars:
      # ===========================================
      # REQUIRED: Node.js Environment
      # ===========================================
      - key: NODE_ENV
        value: production

      # ===========================================
      # REQUIRED: Port (auto-assigned by Render)
      # ===========================================
      - key: PORT
        value: 10000

      # ===========================================
      # REQUIRED: Session Security
      # Auto-generated secure random string
      # ===========================================
      - key: SESSION_SECRET
        generateValue: true

      # ===========================================
      # REQUIRED: Supabase Database Configuration
      # ⚠️ USER MUST CONFIGURE THESE DURING DEPLOY
      # Get from: https://supabase.com → Settings → API
      # ===========================================
      - key: SUPABASE_URL
        sync: false
        # Example: https://abcdefgh.supabase.co
        # Instructions:
        # 1. Create Supabase project at https://supabase.com
        # 2. Navigate to Settings → API
        # 3. Copy "Project URL"

      - key: SUPABASE_ANON_KEY
        sync: false
        # Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        # Instructions:
        # 1. In Supabase Settings → API
        # 2. Copy "anon public" key (NOT service_role!)
        # 3. This is the public key, safe for client-side

      # ===========================================
      # OPTIONAL: Setup Wizard Control
      # ===========================================
      - key: SETUP_MODE
        value: enabled
        # Set to 'disabled' after initial setup if desired

      # ===========================================
      # OPTIONAL: Google Docs Integration (Legacy)
      # ===========================================
      - key: GOOGLE_DOC_ID
        sync: false
        # Example: 1abc123def456ghi789jkl
        # Only needed for Google Docs import feature
        # Extract from URL: docs.google.com/document/d/[THIS_PART]/edit

      # ===========================================
      # AUTO-CONFIGURED: App URL
      # Render automatically sets this based on your deployment
      # Format: https://your-app-name.onrender.com
      # ===========================================
      # APP_URL is available as process.env.RENDER_EXTERNAL_URL
      # or defaults to http://localhost:3000 in development

# ==============================================================================
# DEPLOYMENT INSTRUCTIONS
# ==============================================================================
#
# 📋 BEFORE DEPLOYING:
# 1. Create Supabase project:
#    - Visit https://supabase.com and create new project
#    - Run database migrations (see /docs/DATABASE_MIGRATIONS.md)
#    - Note down Project URL and Anon Key from Settings → API
#
# 2. Prepare environment variables:
#    - SUPABASE_URL from Supabase dashboard
#    - SUPABASE_ANON_KEY from Supabase dashboard
#    - SESSION_SECRET will be auto-generated by Render
#
# 🚀 TO DEPLOY:
# Option 1: One-Click Deploy
#   - Click "Deploy to Render" button
#   - Fill in SUPABASE_URL and SUPABASE_ANON_KEY
#   - Click "Apply"
#
# Option 2: Manual Deploy
#   - Go to https://render.com/dashboard
#   - Click "New +" → "Web Service"
#   - Connect repository and follow prompts
#   - Set environment variables in Render dashboard
#
# ✅ AFTER DEPLOYMENT:
# 1. Visit your app URL (https://your-app.onrender.com)
# 2. Complete setup wizard:
#    - Organization information
#    - Hierarchy configuration
#    - Document upload
# 3. Verify health check: https://your-app.onrender.com/api/health
#
# 📚 DOCUMENTATION:
# - Full deployment guide: /docs/RENDER_DEPLOYMENT.md
# - Environment variables: /docs/ENV_SETUP.md
# - Database migrations: /docs/DATABASE_MIGRATIONS.md
# - Deployment checklist: /docs/DEPLOYMENT_CHECKLIST.md
#
# ==============================================================================
# NOTES
# ==============================================================================
#
# 💾 DATABASE:
# - This app uses Supabase (PostgreSQL)
# - No additional Render database required
# - Keeps hosting on free tier!
#
# 📁 FILE STORAGE:
# - Currently uses local ephemeral disk
# - Files used for setup wizard only (temporary)
# - Documents parsed immediately, can be deleted after
# - For persistent storage, consider Supabase Storage (future)
#
# 🔒 SECURITY:
# - HTTPS enforced automatically by Render
# - SESSION_SECRET auto-generated (secure)
# - Use SUPABASE_ANON_KEY only (not service_role)
# - Enable Row Level Security (RLS) in Supabase
#
# 📊 MONITORING:
# - Health check at /api/health
# - Logs available in Render dashboard
# - Set up alerts in Render settings
#
# 💰 COST:
# - Free tier: $0/month (with spin-down after 15 min)
# - Starter: $7/month (always-on, 1GB RAM)
# - Standard: $25/month (2GB RAM, scaling)
#
# 🔄 UPDATES:
# - Auto-deploy enabled on push to main branch
# - Manual deploy available in Render dashboard
# - Rollback to previous deployment anytime
#
# ==============================================================================
